l=read.csv("C:/Users/bhara/OneDrive/Apps/da lab/LungCap.csv")
l=data.frame(l)
nrow(l)
ncol(l)
print(l)
head(l)
tail(l)
table(l$Age)
table(l$Height)
table(l$Smoke)
table(l$Gender)
table(l$Caesarean)
table(l$LungCap)
table(l$Smoke)/nrow(l)
table(l$Smoke)/nrow(l)*100
table(l$Gende,l$Smoke)
min(l$Age)
max(l$Age)
mean(l$Age)
median(l$Age)
quantile(l$Age,probs = 0.25)
quantile(l$Age,probs = 0.5)
quantile(l$Age,probs = 0.75)
quantile(l$Age,probs = 1)
range(l$Age)
sd(l$Age)
summary(l$Age)
summary(l)
boxplot(l$Age,main="age attribute",ylab="age")
boxplot(l$Age,main="age attribute",ylab="age",horizontal=TRUE)
boxplot(l$LungCap~l$Gender,main="lung cap v/s gender",xlab=NULL)
boxplot(l$LungCap~l$Smoke,main="lung cap v/s gender",xlab=NULL)
boxplot(LungCap~Smoke,data=l[l$Age>=18,],main="lung cap v/s smole",xlab="smooke",ylab ="lung cap")
agegroup=cut(l$Age,breaks = c(0,13,15,17,25),labels = c("<13","14/15","16/17",">=18"))
boxplot(l$LungCap~l$Smoke*agegroup,main="lung cap v/s smoke",ylab="lung cap",xlab=NULL)